### ISSUE TITLE
Npm run watch missing file error resulting in Firefox Nightly being unresponsive

### ISSUE THREAD

**Issue by thessakranendonk** [mozilla-extensions/nimbus-devtools#2]
When running npm run watch in the terminal the following error showed up resulting in Firefox Nightly being unresponsive. Nimbus.json is not present in the dist folder after the build has been completed. When nimbus.json gets manually entered Firefox Nightly runs as it should without errors. See error message below:

WebExtError: installTemporaryAddon: Error: Error: Could not install add-on at '/Users/***/Documents/projects/mozilla/nimbus-devtools/dist': Error: Error while loading 'file:///Users/***/Documents/projects/mozilla/nimbus-devtools/dist/apis/nimbus.json' (NS_ERROR_FILE_NOT_FOUND)

**Comment by thessakranendonk** [comment]
See PR #3

**Comment by brennie** [comment]
Fixed by #3
